CREATE TABLE about (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(255),
                       full_description TEXT,
                       github_url VARCHAR(255),
                       linkedin_url VARCHAR(255),
                       location VARCHAR(255),
                       phone VARCHAR(255),
                       profile_image_url VARCHAR(255),
                       resume_url VARCHAR(255),
                       short_description TEXT,
                       title VARCHAR(255) NOT NULL
);

CREATE TABLE certificates (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              certificate_url VARCHAR(255),
                              credential_id VARCHAR(255),
                              credential_url VARCHAR(255),
                              description TEXT,
                              display_order INTEGER,
                              expiry_date VARCHAR(255),
                              issue_date VARCHAR(255),
                              issuing_organization VARCHAR(255) NOT NULL,
                              title VARCHAR(255) NOT NULL
);

CREATE TABLE contacts (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255) NOT NULL,
                          message TEXT NOT NULL,
                          name VARCHAR(255) NOT NULL,
                          subject VARCHAR(255)
);

CREATE TABLE education (
                           id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           degree VARCHAR(255) NOT NULL,
                           description TEXT,
                           display_order INTEGER,
                           end_date VARCHAR(255),
                           field_of_study VARCHAR(255),
                           grade VARCHAR(255),
                           institution VARCHAR(255) NOT NULL,
                           location VARCHAR(255),
                           start_date VARCHAR(255) NOT NULL
);

CREATE TABLE experiences (
                             id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                             company VARCHAR(255) NOT NULL,
                             current BOOLEAN NOT NULL,
                             description TEXT,
                             display_order INTEGER,
                             end_date VARCHAR(255),
                             location VARCHAR(255),
                             role VARCHAR(255) NOT NULL,
                             start_date VARCHAR(255) NOT NULL,
                             technologies VARCHAR(255)
);

CREATE TABLE learning_items (
                                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                category VARCHAR(255),
                                description TEXT,
                                display_order INTEGER NOT NULL,
                                start_date VARCHAR(255),
                                status VARCHAR(255),
                                target_date VARCHAR(255),
                                title VARCHAR(255) NOT NULL,
                                visible BOOLEAN NOT NULL
);

CREATE TABLE media (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       category VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                       file_size BIGINT NOT NULL,
                       file_type VARCHAR(255) NOT NULL,
                       original_name VARCHAR(255) NOT NULL,
                       stored_name VARCHAR(255) NOT NULL,
                       url VARCHAR(255) NOT NULL
);

CREATE TABLE projects (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          description TEXT,
                          display_order INTEGER,
                          github_url VARCHAR(255),
                          image_url VARCHAR(255),
                          live_url VARCHAR(255),
                          published BOOLEAN NOT NULL,
                          technologies TEXT,
                          title VARCHAR(255)
);

CREATE TABLE skills (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        category VARCHAR(255) NOT NULL,
                        display_order INTEGER,
                        featured BOOLEAN NOT NULL,
                        icon_url VARCHAR(255),
                        name VARCHAR(255) NOT NULL,
                        proficiency INTEGER
);

CREATE TABLE social_links (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              display_order INTEGER,
                              platform VARCHAR(255) NOT NULL,
                              url VARCHAR(255) NOT NULL,
                              visible BOOLEAN NOT NULL
);

CREATE TABLE training (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          certificate_url VARCHAR(255),
                          current BOOLEAN NOT NULL,
                          description TEXT,
                          display_order INTEGER NOT NULL,
                          end_date VARCHAR(255),
                          location VARCHAR(255),
                          organization VARCHAR(255) NOT NULL,
                          start_date VARCHAR(255),
                          title VARCHAR(255) NOT NULL
);